/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'service-offers': ServiceOffer;
    footers: Footer;
    'navigation-bars': NavigationBar;
    'subscription-forms': SubscriptionForm;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'service-offers': ServiceOffersSelect<false> | ServiceOffersSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    'navigation-bars': NavigationBarsSelect<false> | NavigationBarsSelect<true>;
    'subscription-forms': SubscriptionFormsSelect<false> | SubscriptionFormsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  serviceOffers?: (number | null) | ServiceOffer;
  navigationBar?: (number | null) | NavigationBar;
  dynamicZone?: (HeroBlock | PromoBlock | ProductGridBlock)[] | null;
  subscriptionForm?: (number | null) | SubscriptionForm;
  footer?: (number | null) | Footer;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-offers".
 */
export interface ServiceOffer {
  id: number;
  title: string;
  layout?: ListItemBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListItemBlock".
 */
export interface ListItemBlock {
  text?: string | null;
  link?: string | null;
  iconField?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'list-item';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-bars".
 */
export interface NavigationBar {
  id: number;
  title: string;
  layout?: NavigationBarBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationBarBlock".
 */
export interface NavigationBarBlock {
  layout?: (FirstLevelBlock | SecondLevelBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Navigation Bar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FirstLevelBlock".
 */
export interface FirstLevelBlock {
  leftIconList?: ListItemBlock[] | null;
  title?: string | null;
  rightIconList?: ListItemBlock[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'First Level';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecondLevelBlock".
 */
export interface SecondLevelBlock {
  layout?: ListItemBlock[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Second Level';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading?: string | null;
  subheading?: string | null;
  subtitle?: string | null;
  layout?: (ButtonBlock | ImageBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  text: string;
  link: string;
  iconField?: string | null;
  variant?: ('primary' | 'secondary' | 'tertiary') | null;
  size?: ('small' | 'medium' | 'large') | null;
  openInNewTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  description?: string | null;
  link?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBlock".
 */
export interface PromoBlock {
  heading?: string | null;
  subheading?: string | null;
  subtitle?: string | null;
  body?: string | null;
  layout?: (ButtonBlock | ImageBlock)[] | null;
  links?:
    | {
        text?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Promo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock".
 */
export interface ProductGridBlock {
  heading?: string | null;
  subheading?: string | null;
  layout?: ImageBlock[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ProductGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-forms".
 */
export interface SubscriptionForm {
  id: number;
  title: string;
  layout?: SubscriptionFormBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubscriptionFormBlock".
 */
export interface SubscriptionFormBlock {
  heading?: string | null;
  subheading?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: FormBlock[] | null;
  privacyStatement?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SubscriptionForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  heading?: string | null;
  subheading?: string | null;
  layout?: (InputBlock | ButtonBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InputBlock".
 */
export interface InputBlock {
  label?: string | null;
  placeholder?: string | null;
  helperText?: string | null;
  type: 'text' | 'email' | 'password';
  id?: string | null;
  blockName?: string | null;
  blockType: 'Input';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: number;
  title: string;
  layout?: FooterBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock".
 */
export interface FooterBlock {
  navColumns?:
    | {
        title?: string | null;
        layout?: ListItemBlock[] | null;
        id?: string | null;
      }[]
    | null;
  socialMedia?: ListItemBlock[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Footer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'service-offers';
        value: number | ServiceOffer;
      } | null)
    | ({
        relationTo: 'footers';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'navigation-bars';
        value: number | NavigationBar;
      } | null)
    | ({
        relationTo: 'subscription-forms';
        value: number | SubscriptionForm;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  serviceOffers?: T;
  navigationBar?: T;
  dynamicZone?:
    | T
    | {
        Hero?: T | HeroBlockSelect<T>;
        Promo?: T | PromoBlockSelect<T>;
        ProductGrid?: T | ProductGridBlockSelect<T>;
      };
  subscriptionForm?: T;
  footer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  subtitle?: T;
  layout?:
    | T
    | {
        Button?: T | ButtonBlockSelect<T>;
        Image?: T | ImageBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock_select".
 */
export interface ButtonBlockSelect<T extends boolean = true> {
  text?: T;
  link?: T;
  iconField?: T;
  variant?: T;
  size?: T;
  openInNewTab?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  description?: T;
  link?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBlock_select".
 */
export interface PromoBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  subtitle?: T;
  body?: T;
  layout?:
    | T
    | {
        Button?: T | ButtonBlockSelect<T>;
        Image?: T | ImageBlockSelect<T>;
      };
  links?:
    | T
    | {
        text?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock_select".
 */
export interface ProductGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  layout?:
    | T
    | {
        Image?: T | ImageBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-offers_select".
 */
export interface ServiceOffersSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        'list-item'?: T | ListItemBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListItemBlock_select".
 */
export interface ListItemBlockSelect<T extends boolean = true> {
  text?: T;
  link?: T;
  iconField?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        Footer?: T | FooterBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock_select".
 */
export interface FooterBlockSelect<T extends boolean = true> {
  navColumns?:
    | T
    | {
        title?: T;
        layout?:
          | T
          | {
              'list-item'?: T | ListItemBlockSelect<T>;
            };
        id?: T;
      };
  socialMedia?:
    | T
    | {
        'list-item'?: T | ListItemBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-bars_select".
 */
export interface NavigationBarsSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        'Navigation Bar'?: T | NavigationBarBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationBarBlock_select".
 */
export interface NavigationBarBlockSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        'First Level'?: T | FirstLevelBlockSelect<T>;
        'Second Level'?: T | SecondLevelBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FirstLevelBlock_select".
 */
export interface FirstLevelBlockSelect<T extends boolean = true> {
  leftIconList?:
    | T
    | {
        'list-item'?: T | ListItemBlockSelect<T>;
      };
  title?: T;
  rightIconList?:
    | T
    | {
        'list-item'?: T | ListItemBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecondLevelBlock_select".
 */
export interface SecondLevelBlockSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        'list-item'?: T | ListItemBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-forms_select".
 */
export interface SubscriptionFormsSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        SubscriptionForm?: T | SubscriptionFormBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubscriptionFormBlock_select".
 */
export interface SubscriptionFormBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?:
    | T
    | {
        text?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        Form?: T | FormBlockSelect<T>;
      };
  privacyStatement?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  layout?:
    | T
    | {
        Input?: T | InputBlockSelect<T>;
        Button?: T | ButtonBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InputBlock_select".
 */
export interface InputBlockSelect<T extends boolean = true> {
  label?: T;
  placeholder?: T;
  helperText?: T;
  type?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}